### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by horstepipe** [geluk/matrix-webhook-gateway#75]
Hello
Since some days that nice plugin doesn't start anymore. 
I'm getting this error:

```
/home/user/scripts/webhook-gateway/node_modules/ttypescript/lib/loadTypescript.js:29
    var _e = ts.versionMajorMinor.split('.'), major = _e[0], minor = _e[1];
                                  ^

TypeError: Cannot read properties of undefined (reading 'split')
    at Object.loadTypeScript (/home/user/scripts/webhook-gateway/node_modules/ttypescript/lib/loadTypescript.js:29:35)
    at Object.<anonymous> (/home/user/scripts/webhook-gateway/node_modules/ttypescript/lib/typescript.js:3:27)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/user/scripts/webhook-gateway/src/webhooks/PluginCollection.js:61:26)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
```

Anybody got an idea how to fix that?

**Comment by geluk** [comment]
Is it possible that you updated some packages? Or maybe node.js itself? Otherwise I'm not quite sure how this could suddenly stop working.

**Comment by horstepipe** [comment]
sorry I updated to the latest release and it was working again!
