### ISSUE TITLE
TypeError since last Node.js v18.17.1

### ISSUE THREAD

**Issue by Dual-0** [geluk/matrix-webhook-gateway#78]
Hello,

since the last node update I got this error message:

```
root@COM:/opt/webhook-gateway# node entry.js
/opt/webhook-gateway/node_modules/ttypescript/lib/loadTypescript.js:13
        function __() { this.constructor = d; }
                                         ^

TypeError: Cannot set property constructor of [object Object] which has only a getter
    at new __ (/opt/webhook-gateway/node_modules/ttypescript/lib/loadTypescript.js:13:42)
    at __extends (/opt/webhook-gateway/node_modules/ttypescript/lib/loadTypescript.js:14:84)
    at /opt/webhook-gateway/node_modules/ttypescript/lib/loadTypescript.js:65:5
    at Object.<anonymous> (/opt/webhook-gateway/node_modules/ttypescript/lib/loadTypescript.js:100:2)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)

Node.js v18.17.1
```

**Comment by horstepipe** [comment]
Hey
I'm seeing the same with Node.js v20.6.0.

Best regards
